.TH VPIXX 1
.SH NAME
vpixx \- remotely configure VPIXX projector
.SH SYNOPSIS
.B vpixx
[\fB\-L\fR]
[\fB\-\-led-on\fR]
[\fB\-l\fR]
[\fB\-\-led-off\fR]
[\fB\-a\fR]
[\fB\-\-awake\fR]
[\fB\-s\fR]
[\fB\-\-sleep\fR]
[\fB\-f\fR]
[\fB\-\-front\fR]
[\fB\-r\fR]
[\fB\-\-rear\fR]
[\fB\-i\fR]
[\fB\-\-info\fR]
.SH DESCRIPTION
.B vpixx
remotely changes settings on VPIXX projector.
.SH OPTIONS
.TP
.BR \-L ", " \-\-led-on\fR
Turn on the VPIXX LED light.
.TP
.BR \-l ", " \-\-led-off\fR
Turn off the VPIXX LED light.
.TP
.BR \-a ", " \-\-awake\fR
Awaken the VPIXX from sleeping state.
.TP
.BR \-s ", " \-\-sleep\fR
Put the VPIXX into a sleeping state.
.TP
.BR \-f ", " \-\-front\fR
Set the VPIXX in front projection mode.
.TP
.BR \-r ", " \-\-rear\fR
Set the VPIXX in rear projection mode.
.TP
.BR \-i ", " \-\-info\fR
Print some info about the VPIXX.
